# Generated by Django 3.2.12 on 2022-04-04 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('typeforms', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='field',
            old_name='name',
            new_name='label',
        ),
    ]
