# Generated by Django 3.2.12 on 2022-04-05 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('typeforms', '0002_rename_name_field_label'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='field',
            options={'ordering': ('order', 'created_at')},
        ),
        migrations.AlterModelOptions(
            name='fieldoption',
            options={'ordering': ('order', 'created_at')},
        ),
        migrations.AlterModelOptions(
            name='form',
            options={'ordering': ('created_at',)},
        ),
        migrations.RemoveField(
            model_name='field',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='fieldoption',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='fieldsubmission',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='form',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='formsubmission',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='field',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='fieldoption',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='fieldsubmission',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='form',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='field',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='field',
            name='deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='fieldoption',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='fieldoption',
            name='deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='fieldsubmission',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='fieldsubmission',
            name='deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='form',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='form',
            name='deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='formsubmission',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='formsubmission',
            name='deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
