# Generated by Django 3.2.12 on 2022-04-05 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('typeforms', '0003_auto_20220405_1102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fieldoption',
            name='name',
        ),
        migrations.AddField(
            model_name='fieldoption',
            name='text',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='field',
            name='type',
            field=models.CharField(choices=[('text', 'Text'), ('textarea', 'Textarea'), ('number', 'Number'), ('date', 'Date'), ('time', 'Time'), ('email', 'Email'), ('url', 'Url'), ('password', 'Password'), ('select', 'Select'), ('radio', 'Radio')], max_length=100),
        ),
    ]
