# Generated by Django 3.2.12 on 2022-04-05 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('typeforms', '0004_auto_20220405_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='multiple',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
